export * from './functions'
export * from './insert-one-adapter.protocol'
export * from './get-one-adapter.protocol'
export * from './update-one-adapter.protocol'
export * from './delete-one-adapter.protocol'
export * from './get-all-adapter.protocol'
