export * from './insert-one-function.protocol'
export * from './get-one-function.protocol'
export * from './update-one-function.protocol'
export * from './delete-one-function.protocol'
export * from './get-all-function.protocol'
export * from './get-many-function.protocol'
