export * from './insert-one-factory.protocol'
export * from './get-one-factory.protocol'
export * from './update-one-factory.protocol'
export * from './delete-one-factory.protocol'
export * from './get-all-factory.protocol'
